Update nc-easyssl

diff --git a/nc-easyssl b/nc-easyssl
--- a/nc-easyssl
+++ b/nc-easyssl
@@ -50,10 +50,13 @@ function checkrequirements() {
 		command -v $command >/dev/null 2>&1 || { echo "ERROR: This script requires $command but it's not installed. Aborting." >&2; exit 123; }
 	done
 	
-	if [[ $(pip list 2>/dev/null| grep certbot-dns-netcup | wc -l) -ne 1 ]]; then
-		echo "ERROR: certbot-dns-netcup not found. Please install certbot-dns-netcup via pip. Aborting."
-		exit 123
-	fi
+	modules=(setuptools certbot-dns-netcup)
+	for module in $modules; do
+		if [[ $(pip list 2>/dev/null| grep $module | wc -l) -ne 1 ]]; then
+			echo "ERROR: $module not found. Please install $module via pip. Aborting."
+			exit 123
+		fi
+	done
 }
 
 cd "$(dirname "${BASH_SOURCE[0]}")" || {
